services:
  backend:
    image: ecommerce:latest
    restart: always
    ports:
      - 3333:3333
    environment:
      - DB_HOST=db
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_PASSWORD=root

    expose:
      - 5432
    ports:
      - 5432:5432
volumes:
  db-data:
networks:
  spring-postgres:
